FROM ghcr.io/pnpm/pnpm:12.0.0 AS base
RUN pnpm runtime set node 26.8.1 -g
WORKDIR /app

FROM base AS dependencies
COPY pnpm-lock.yaml pnpm-workspace.yaml package.json ./
COPY apps/ ./apps/
RUN find apps -type f ! -name 'package.json' -delete
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

FROM base AS web
COPY --from=dependencies /app/node_modules ./node_modules
COPY --from=dependencies /app/apps/ ./app
COPY package.json pnpm-workspace.yaml ./
COPY apps/ ./apps/
EXPOSE 8787
CMD ["pnpm", "--filter", "web", "dev"]
