name: web-app-checks
run-name: Portfolio's Web app checks
on:
  pull_request:
    branches:
      - main
    paths:
      - package.json
      - pnpm-lock.yaml
      - pnpm-workspace.yaml
      - '.github/workflows/web-app-checks.yml'
      - 'apps/web/**'

jobs:
  test-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    env:
      WRANGLER_SEND_METRICS: false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7.0.1

      - name: Setup pnpm and Node.js
        uses: pnpm/setup@v1
        with:
          runtime: node@26.8.1
          install: false
          cache: true

      - name: Instal dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Build OpenNext worker
        run: |
          pnpm --filter web exec opennextjs-cloudflare build

      - name: Measure bundle compressed size
        id: dry_run
        run: |
          pnpm --filter web size

      - name: Reporting dry-run execution
        uses: mshick/add-pr-comment@v3
        if: always()
        with:
          message: ${{ steps.dry_run.outputs.size }}
