name: web-app-checks
run-name: Portfolio's Web app checks
on:
  pull_request:
    branches:
      - main
    paths:
      - package.json
      - pnpm-lock.yaml
      - pnpm-workspace.yaml
      - '.github/workflows/web-app-checks.yml'
      - 'apps/web/**'

jobs:
  test-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    env:
      WRANGLER_SEND_METRICS: false
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PR_NUMBER: ${{ github.event.pull_request.number }}
      GH_REPO: ${{ github.repository }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7.0.1

      - name: Setup pnpm and Node.js
        uses: pnpm/setup@v1
        with:
          runtime: node@26.8.1
          install: false
          cache: true

      - name: Instal dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Store Playwright CLI version
        id: playwright-version
        run: |
          echo "PLAYWRIGHT_VERSION=$(pnpm exec playwright --version | cut -d' ' -f2)" >> $GITHUB_ENV

      - name: Cache Playwright Browsers
        id: playwright-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ env.PLAYWRIGHT_VERSION }}

      - name: Install Playwright OS dependencies & Chromium
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: |
          pnpm exec --filter web playwright install --with-deps chromium

      - name: Install Playwright OS system dependencies only (if browser cached)
        if: steps.playwright-cache.outputs.cache-hit == 'true'
        run: |
          pnpm exec --filter web playwright install-deps chromium

      - name: Run Typescript checks
        run: |
          pnpm --filter web ts:check

      - name: Run Unit tests
        run: |
          pnpm --filter web test

      - name: Run Browser tests
        run: |
          pnpm --filter web test:browser

      - name: Build OpenNext worker
        run: |
          pnpm --filter web run build:cf

      - name: Measure bundle compressed size
        continue-on-error: true
        run: |
          set -o pipefail
          pnpm --filter web size | sed -n '/✨ Read/,$p' > report.md

      - name: Reporting dry-run execution
        if: always()
        run: |
          gh pr comment "${PR_NUMBER:?Missing PR_NUMBER}" --body-file report.md --edit-last --create-if-none
